package Mountain8848.molecular.model.posttransitionmetals;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Moleculyar
//  @ File Name : Al.java
//  @ Date : 24.09.2017
//  @ Author : 
//
//




public class Al implements PostTransitionMetal {

	public int getNuclearCharge() {
		return 13;
	}

	public double getAtomicMass() {
		// TODO Auto-generated method stub
		return 26.98;
	}


}
