package Mountain8848.molecular.model.posttransitionmetals;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Moleculyar
//  @ File Name : Pd.java
//  @ Date : 24.09.2017
//  @ Author : 
//
//







public class Pd implements PostTransitionMetal {

	public int getNuclearCharge() {
		// TODO Auto-generated method stub
		return 82;
	}

	public double getAtomicMass() {
		// TODO Auto-generated method stub
		return 207.20;
	}


}
