package Mountain8848.molecular.model.posttransitionmetals;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Moleculyar
//  @ File Name : Sn.java
//  @ Date : 24.09.2017
//  @ Author : 
//
//





public class Sn implements PostTransitionMetal {

	public int getNuclearCharge() {
		return 50;
	}

	public double getAtomicMass() {
		// TODO Auto-generated method stub
		return 118.69;
	}


}
