package Mountain8848.molecular.model.transitionmetals;

import Mountain8848.molecular.model.Element;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Moleculyar
//  @ File Name : Transition metals.java
//  @ Date : 24.09.2017
//  @ Author : 
//
//




public interface TransitionMetal extends Element {

   @Override
   default String getGroupName() {
      return TransitionMetal.class.getSimpleName();
   }
   
}
