package Mountain8848.molecular.model.element.transitionmetals;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Moleculyar
//  @ File Name : Cu.java
//  @ Date : 24.09.2017
//  @ Author : 
//
//

public class Cu implements TransitionMetal {

	public int getNuclearCharge() {
		return 29;
	}

	public double getAtomicMass() {
		// TODO Auto-generated method stub
		return 63.55;
	}


}
