package Mountain8848.molecular.model.element.transitionmetals;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Moleculyar
//  @ File Name : Fe.java
//  @ Date : 24.09.2017
//  @ Author : 
//
//

public class Fe implements TransitionMetal {

	public int getNuclearCharge() {
		return 26;
	}

	public double getAtomicMass() {
		// TODO Auto-generated method stub
		return 55.85;
	}


}
