package Mountain8848.molecular.model.nometals;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Moleculyar
//  @ File Name : C.java
//  @ Date : 24.09.2017
//  @ Author : 
//
//

public class C implements Nometal {

	public int getNuclearCharge() {
		
		return 6;
	}

	public double getAtomicMass() {
		// TODO Auto-generated method stub
		return 12.01;
	}

	
}
