package Mountain8848.molecular.model.nometals;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Moleculyar
//  @ File Name : H.java
//  @ Date : 24.09.2017
//  @ Author : 
//
//

public class H implements Nometal {

	public int getNuclearCharge() {
		
		return 1;
	}

	public double getAtomicMass() {
		// TODO Auto-generated method stub
		return 1.01;
	}


	
}
